"""HTTP request/response models for the FastAPI service.

Kept intentionally explicit so the OpenAPI docs (auto-generated by FastAPI) are
self-describing and the frontend has a 1:1 contract to code against.
"""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from packages.core.schemas.chunk import ParsedChunk
from packages.core.schemas.document import DocumentMeta
from packages.core.schemas.evidence import Answer, RetrievalHit


# --------------------------------------------------------------------------- #
# Documents / ingest / parse / index
# --------------------------------------------------------------------------- #
class IngestResponse(BaseModel):
    document_id: str
    filename: str
    page_count: int
    parser: str
    status: Literal["success", "failed", "partial"]
    sha256: str
    errors: list[str] = Field(default_factory=list)


class DocumentListResponse(BaseModel):
    documents: list[DocumentMeta]
    total: int


class ParseRequest(BaseModel):
    parser: Literal["baseline", "docling"] = "baseline"
    document_ids: list[str] | None = None  # None => all pending


class ParseResponse(BaseModel):
    parser: str
    processed: int
    succeeded: int
    failed: int
    chunks: int
    errors: list[str] = Field(default_factory=list)


class IndexRequest(BaseModel):
    parser: Literal["baseline", "docling", "any"] = "any"
    document_ids: list[str] | None = None


class IndexResponse(BaseModel):
    indexed_chunks: int
    collection: str
    vector_dim: int
    status: Literal["success", "failed", "partial"] = "success"
    errors: list[str] = Field(default_factory=list)


# --------------------------------------------------------------------------- #
# Search / QA
# --------------------------------------------------------------------------- #
class SearchRequest(BaseModel):
    query: str
    top_k: int | None = None
    filters: dict[str, Any] | None = None  # e.g. {"domain": "finance_regulatory"}


class SearchResponse(BaseModel):
    query: str
    hits: list[RetrievalHit]
    total: int


class QARequest(BaseModel):
    question: str
    top_k: int | None = None
    filters: dict[str, Any] | None = None


# Re-export Answer so API users import a single module.
__all__ = [
    "IngestResponse",
    "DocumentListResponse",
    "ParseRequest",
    "ParseResponse",
    "IndexRequest",
    "IndexResponse",
    "SearchRequest",
    "SearchResponse",
    "QARequest",
    "Answer",
    "ParsedChunk",
]
